### ISSUE TITLE
Download script stopped working earlier today, now consistently fails with "cound not get zippyshare url algorithm"

### ISSUE THREAD

**Issue by mary-kate** [img2tab/zippyshare#3]
Some 15-ish hours ago or so the zippyshare downloader script started consistently failing with the "cound not get zippyshare url algorithm" error message. I presume zippyshare changed the algorithm somehow, but alas, I haven't been able to fix this on my own...

**Comment by ffluegel** [comment]
I found a solution and created a pull request.

**Comment by tyathalae** [comment]
Thanks, you beat me to it.

**Comment by IamMrZ** [comment]
Using this pull, now fails with "could not download file"

**Comment by ahmedtds** [comment]
I'm getting this error

> zippyshare.sh: line 7: syntax error near unexpected token `newline'
> zippyshare.sh: line 7: `<!DOCTYPE html>'

Will there be a fix?

**Comment by ahmedtds** [comment]
@ffluegel it works, thanks a lot. sorry missed it before you said :)

**Comment by img2tab** [comment]
Merging branch from ffluegel.
