### ISSUE TITLE
Getting Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by AlexanderProd** [img2tab/zippyshare#5]
When trying to download something I get wether or not I use a link file or single link
`zippyshare.sh: 17: zippyshare.sh: Syntax error: "(" unexpected`

I'm using Ubuntu server 18.04

**Comment by ffluegel** [comment]
Please check my [fork](https://github.com/ffluegel/zippyshare) for a fixed version.

**Comment by AlexanderProd** [comment]
@ffluegel Thanks but I'm still getting the same error. -.-

**Comment by AlexanderProd** [comment]
@ffluegel thanks its working now.
